server.port: 8081

spring:
  profiles:
    active: mariadb
    group:
      mariadb: local-mariadb

upbit:
  accessKey: ${accessKey:NONE}
  secretKey: ${secretKey:NONE}
  markets: ${markets:KRW-BTC}
  candleMinutes: ${candleMinutes:5}
  longBlueCandleRate: ${longBlueCandleRate:0.004}
  lossCutRate: ${lossCutRate:0.02}
  balancePerLevel: ${balancePerLevel:10000.0,20000.0,30000.0,40000.0,50000.0}
  marginRatePerLevel: ${marginRatePerLevel:0.005,0.004,0.003,0.002,0.001}
  scaleTradeRatePerLevel: ${scaleTradeRatePerLevel:0.004,0.005,0.006,0.007,0.008}
---

spring:
  config:
    activate:
      on-profile: local-mariadb
  datasource:
    url: jdbc:mariadb://192.168.56.100:3306/UPBIT
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
    hikari:
      connection-timeout: 60000 # 1min
      maximum-pool-size: 20
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create # 변경된 스키마만 적용 (none/update/validate/create/create-drop)

mybatis:
  type-aliases-package: kr.co.fastcampus.eatgo
  mapper-locations: mybatis/mapper/*.xml